version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      echo "Verifying source files..."
      ls -l
  build:
    commands:
      echo "Build started on `date`"
      echo "No complex build steps needed for static HTML."
  post_build:
    commands:
      echo "Build completed on `date`"

artifacts:
  files:
    - index.html
